spring:
  elasticsearch:
    rest:
      uris: ${openea.elasticsearch.uris}
      username: ${openea.elasticsearch.username}
      password: ${openea.elasticsearch.password}

openea:
  indices:
    show: sys-log-*,mysql-slowlog-*,sys_user,point-log-*,audit-log-*
  swagger:
    enabled: true
    title: 搜索中心
    description: 搜索中心接口文档
    version: 1.0
    base-package: org.openea.search.controller
